spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    url: "jdbc:h2:mem:todoapp;DB_CLOSE_ON_EXIT=FALSE" #nombre tabla bdd
  h2: #habilitación bdd h2
    console:
      enabled: true
      path: /h2-console
  jpa: #configuracion jpa para mostrar querys
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate: #configuracion hibernate para volver a crear tablas cada vez que iniciemos
      ddl-auto: create-drop
